"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T12:31:02.490884+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sha2, concat, current_date, current_timestamp, input_file_name, row_number, broadcast, coalesce
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, DecimalType, TimestampType
import sys

# Initialize Spark Session
spark = SparkSession.builder.appName("PartnerFeedPipeline").getOrCreate()

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("merchant_id", StringType(), True),
        StructField("customer_id", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("payment_method", StringType(), True),
        StructField("txn_timestamp", StringType(), True),
        StructField("merchant_rating", StringType(), True)
    ])
    
    # Read the CSV file with specified schema
    df = spark.read.csv(input_path, schema=schema, header=True)
    
    # Add metadata columns
    df = df.withColumn("ingestion_timestamp", current_timestamp()) \
           .withColumn("source_file_name", input_file_name()) \
          .withColumn("run_date", current_date()) \
           .withColumn("pipeline_run_id", lit(run_id))
    
    # Cast columns to correct types
    df = df.withColumn("amount", col("amount").cast(DecimalType(18,2))) \
           .withColumn("txn_timestamp", col("txn_timestamp").cast(TimestampType()))
    
    # Write the DataFrame to Parquet partitioned by run_date
    df.write.mode("overwrite").partitionBy("run_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read the Bronze layer data
    bronze_df = spark.read.parquet(bronze_path).where(col("run_date") == run_date)
    
    # Cast columns to correct types
    silver_df = bronze_df.withColumn("amount", col("amount").cast(DecimalType(18,2))) \
                          .withColumn("txn_timestamp", col("txn_timestamp").cast(TimestampType())) \
                          .withColumn("merchant_rating", col("merchant_rating").cast(DoubleType()))
    
    # Filter out NULL merchant_id and customer_id and negative amounts
    silver_df = silver_df.where(
        (col("merchant_id").isNotNull()) &
        (col("customer_id").isNotNull()) &
        (col("amount") > 0)
    )
    
    # Deduplicate based on transaction_id, keeping the latest record
    window_spec = Window.partitionBy("transaction_id").orderBy(col("txn_timestamp").desc())
    silver_df = silver_df.withColumn("row_number", row_number().over(window_spec))
    silver_df = silver_df.where(col("row_number") == 1).drop("row_number")
    
    # Read the partner merchant mapping
    merchants_df = spark.read.option("header", "true").csv(merchants_path)
    
    # Broadcast and cache the merchants DataFrame
    merchants_df = broadcast(merchants_df)
    merchants_df.cache()
    
    # Join with the merchants DataFrame
    silver_df = silver_df.join(merchants_df, silver_df.col("merchant_id") == merchants_df.col("merchant_id"), "inner")
    
    # Add quality_flag column
    silver_df = silver_df.withColumn("quality_flag", when((col("merchant_id").isNotNull()) & (col("customer_id").isNotNull()), "CLEAN").otherwise("UNMATCHED"))
    
    # Write the Silver layer data to Parquet partitioned by run_date
    silver_df.write.mode("overwrite").partitionBy("run_date").parquet(output_path)

def main():
    input_path = sys.argv[1]  # Path to the Bronze layer input CSV
    output_path_bronze = sys.argv[2]  # Path to write Bronze layer Parquet
    output_path_silver = sys.argv[3]  # Path to write Silver layer Parquet
    merchants_path = sys.argv[4]  # Path to partner merchant mapping CSV
    run_date = sys.argv[5]  # Run date
    run_id = sys.argv[6]  # Run ID
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, output_path_bronze, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, output_path_bronze, merchants_path, output_path_silver, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sha2, broadcast, coalesce, current_date, current_timestamp, input_file_name, row_number, when, coalesce
from pyspark.sql.types import StringType, DoubleType, DecimalType, TimestampType
from typing import Dict, List, Tuple

def run_gold(spark: SparkSession, silver_path: str, gold_output_dir: str, run_date: str) -> None:
    build_merchant_performance(spark, f"{silver_path}/merchant_performance_silver", f"{gold_output_dir}/merchant_performance_gold", run_date)
    build_customer_ltv(spark, f"{silver_path}/customer_performance_silver", f"{gold_output_dir}/customer_ltv_gold")
    build_daily_summary(spark, f"{silver_path}/transaction_summary_silver", f"{gold_output_dir}/daily_summary_gold", run_date)
    run_metadata = {
        "run_date": run_date,
        "status": "COMPLETED",
        "generated_tables": ["merchant_performance_gold", "customer_ltv_gold", "daily_summary_gold"]
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark: SparkSession, silver_path: str, output_path: str, run_date: str) -> None:
    merchant_performance = (spark.read.format("delta").load(silver_path)
                            .filter(col("status") == "COMPLETED")
                           .groupBy("merchant_id", "merchant_name", "category", "city", "date")
                           .agg(
                                col("merchant_id").alias("merchant_id"),
                                col("merchant_name").alias("merchant_name"),
                                col("category").alias("category"),
                                col("city").alias("city"),
                                col("date").alias("date"),
                                sum("amount").alias("total_revenue"),
                                count("*").alias("txn_count"),
                                (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
                            ))
    merchant_performance.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark: SparkSession, silver_path: str, output_path: str) -> None:
    customer_ltv = (spark.read.format("delta").load(silver_path)
                   .groupBy("customer_id")
                   .agg(
                        col("customer_id").alias("customer_id"),
                        sum("amount").alias("total_spent"),
                        count("*").alias("total_txns"),
                        avg("amount").alias("avg_txn_value"),
                        min("txn_timestamp").alias("first_txn_date"),
                        max("txn_timestamp").alias("last_txn_date"),
                        first(when(col("preferred_payment_method") == "most_frequent", col("payment_method"))).alias("preferred_payment_method")
                    ))
    customer_ltv.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark: SparkSession, silver_path: str, output_path: str, run_date: str) -> None:
    daily_summary = (spark.read.format("delta").load(silver_path)
                     .filter(col("date") == run_date)
                     .groupBy("date")
                    .agg(
                         col("date").alias("date"),
                         sum("amount").alias("total_revenue"),
                         count("*").alias("total_txns"),
                         countDistinct("customer_id").alias("unique_customers"),
                         countDistinct("merchant_id").alias("unique_merchants"),
                         (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
                     ))
    daily_summary.write.partitionBy("date").mode("overwrite").parquet(output_path)
